"""добавил данные поиска

Revision ID: 4ad32ff756cb
Revises: cacc05559fe8
Create Date: 2022-04-28 01:52:18.945828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad32ff756cb'
down_revision = 'cacc05559fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('enter_data', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'enter_data')
    # ### end Alembic commands ###
